config/routes.rb
Rails.application.routes.draw do
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @games = Game.all
    #redirect_to action: 'index'
    respond_to do |format|
        format.html { redirect_to action: 'index', userid: params[:id] }
    end
  end

  # GET /games/new
  def new
    @game = Game.new
    respond_to do |format|
      format.html #new.html.erb
      format.json { render json: @game}
    end
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        #format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :index, status: :created, location: @game }
      else
        #format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      #@game = Game.all
      #@game = Game.find(params[:id])
      #@gamerid = params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:userid, :shot_position, :shot_result, :ship)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(game) do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %>
    <%= f.number_field :userid %>
  </div>

  <div class="field">
    <%= f.label :shot_position %>
    <%= f.text_field :shot_position %>
  </div>

  <div class="field">
    <%= f.label :shot_result %>
    <%= f.check_box :shot_result %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>
<script>
    document.addEventListener("DOMContentLoaded", init, false);
    var ships ={
        0:{
            position_x_inicial: 10,
            posicion_x_final: 80,
            posicion_y_inicial: 10,
            posicion_y_final: 40,
            pos_real_x_init:64,
            pos_real_y_init:64,
            pos_real_x_fin:142,
            pos_real_y_fin:100,
            visible: true
        },
        1:{
            position_x_inicial: 10,
            posicion_x_final: 40,
            posicion_y_inicial: 90,
            posicion_y_final: 40,
            pos_real_x_init:224,
            pos_real_y_init:63,
            pos_real_x_fin:302,
            pos_real_y_fin:102,
            visible: true
        },
        2:{
            position_x_inicial: 90,
            posicion_x_final: 40,
            posicion_y_inicial: 90,
            posicion_y_final: 40,
            pos_real_x_init:64,
            pos_real_y_init:143,
            pos_real_x_fin:102,
            pos_real_y_fin:181,
            visible: true
        },
        3:{
            position_x_inicial: 170,
            posicion_x_final: 80,
            posicion_y_inicial: 10,
            posicion_y_final: 40,
            pos_real_x_init:144,
            pos_real_y_init:144,
            pos_real_x_fin:182,
            pos_real_y_fin:182,
            visible: true
        }
    };
    var ships2 ={
        0:{
            position_x_inicial: 90,
            posicion_x_final: 80,
            posicion_y_inicial: 130,
            posicion_y_final: 40,
            pos_real_x_init:604,
            pos_real_y_init:182,
            pos_real_x_fin:683,
            pos_real_y_fin:221,
            visible: true
        },
        1:{
            position_x_inicial: 10,
            posicion_x_final: 40,
            posicion_y_inicial: 90,
            posicion_y_final: 40,
            pos_real_x_init:685,
            pos_real_y_init:64,
            pos_real_x_fin:763,
            pos_real_y_fin:101,
            visible: true
        },
        2:{
            position_x_inicial: 90,
            posicion_x_final: 40,
            posicion_y_inicial: 90,
            posicion_y_final: 40,
            pos_real_x_init:525,
            pos_real_y_init:143,
            pos_real_x_fin:563,
            pos_real_y_fin:182,
            visible: true
        },
        3:{
            position_x_inicial: 170,
            posicion_x_final: 80,
            posicion_y_inicial: 10,
            posicion_y_final: 40,
            pos_real_x_init:605,
            pos_real_y_init:144,
            pos_real_x_fin:642,
            pos_real_y_fin:179,
            visible: true
        }
    };
    function drawBoard(context){
        for (var x = 0; x <= bw; x += 40) {
            context.moveTo(0.5 + x + p, p);
            context.lineTo(0.5 + x + p, bh + p);
        }


        for (var x = 0; x <= bh; x += 40) {
            context.moveTo(p, 0.5 + x + p);
            context.lineTo(bw + p, 0.5 + x + p);
        }

        context.strokeStyle = "black";
        context.stroke();
        
    }
    function drawShips(context,context2){
    $.each(ships,function(a,b){ 
        //alert(b.position_x_inicial +" "+b.posicion_y_inicial +" "+b.posicion_x_final +" "+b.posicion_y_final);
        context.fillRect(b.position_x_inicial,b.posicion_y_inicial,b.posicion_x_final,b.posicion_y_final);    
    });
    $.each(ships2,function(a,b){ 
        //alert(b.position_x_inicial +" "+b.posicion_y_inicial +" "+b.posicion_x_final +" "+b.posicion_y_final);
        context2.fillRect(b.position_x_inicial,b.posicion_y_inicial,b.posicion_x_final,b.posicion_y_final);    
    });
    
    }
    //grid width and height
    var bw = 400;
    var bh = 400;
    //padding around grid
    var p = 10;
    //size of canvas
    var cw = bw + (p*2) + 1;
    var ch = bh + (p*2) + 1;
    
    function init()
    {
        var canvas = $('<canvas id="canvas" />').attr({width: cw, height: ch}).appendTo('#contentc');
        var canvas2 = $('<canvas id="canvas2" />').attr({width: cw, height: ch}).appendTo('#contentc');
        var context = canvas.get(0).getContext("2d");
        var context2 = canvas2.get(0).getContext("2d");
        var c = document.getElementById("canvas");
        var c2 = document.getElementById("canvas2");
        var con1 = c.getContext("2d");
        drawBoard(context);
        drawBoard(context2);
        if(userid==1){
            //alert("entro");
            c.addEventListener("mousedown", getPosition, false);
        }else{
            //alert("entro2");
            c2.addEventListener("mousedown", getPosition, false);
        }
        drawShips(context,context2);
    }
    
    var getUrlParameter = function getUrlParameter(sParam) {
        var sPageURL = decodeURIComponent(window.location.search.substring(1)),
            sURLVariables = sPageURL.split('&'),
            sParameterName,
            i;

        for (i = 0; i < sURLVariables.length; i++) {
            sParameterName = sURLVariables[i].split('=');

            if (sParameterName[0] === sParam) {
                return sParameterName[1] === undefined ? true : sParameterName[1];
            }
        }
    };
    
    var userid = getUrlParameter('userid');
    //alert(userid);
    
    function getPosition(event)
    {
        
        var x = event.x;
        var y = event.y;
        
        var barco_hundido = 0;
        var barco="";
        
        if(userid==2) {
            $.each(ships2,function(a,b){ 
                //console.log("click");
                //console.log("x " + x + " - y "+ y);
                console.log("ship: "+a);
                //console.log("position_x_inicial "+ b.pos_real_x_init + " - posicion_y_inicial "+ b.pos_real_y_init + " - posicion_x_final" + b.pos_real_x_fin+ " - posicion_y_final " + b.pos_real_y_fin);

                if(x >= b.pos_real_x_init && x <= b.pos_real_x_fin && y >= b.pos_real_y_init && y <= b.pos_real_y_fin){
                    console.log("clicked");
                    barco_hundido = 1;
                    barco = a;
                }else{
                    console.log("no clicked");
                }
            });
            
        }
        
        $.each(ships,function(a,b){ 
            //console.log("click");
            //console.log("x " + x + " - y "+ y);
            console.log("ship: "+a);
            //console.log("position_x_inicial "+ b.pos_real_x_init + " - posicion_y_inicial "+ b.pos_real_y_init + " - posicion_x_final" + b.pos_real_x_fin+ " - posicion_y_final " + b.pos_real_y_fin);

            if(x >= b.pos_real_x_init && x <= b.pos_real_x_fin && y >= b.pos_real_y_init && y <= b.pos_real_y_fin){
                console.log("clicked");
                barco_hundido = 1;
                barco = a;
            }else{
                console.log("no clicked");
            }
        });
        
        
        
        
        $.ajax({
          type: "POST",
          url: "/games",
          data: {game: 
          { 
                userid: userid, 
                shot_position: x + ',' + y, 
                shot_result: barco_hundido,
                ship: barco
          } 
        },
        success:function(data) {
        //alert(data);
        }
        ,error:function(error) {
        }
        });
        
        
        
        
       /* $.post("/games",
        data: {game: 
            { 
            userid: 0, 
            shot_position: "", 
            shot_result: true 
            } 
        },
        function(data) {
              alert(data);
        });*/
 
        
        /*var context = canvas.getContext("2d");
        context.fillStyle = "#000000";
        context.beginPath();
        context.arc(x, y, 50, 0, 2*Math.PI);
        context.fill();*/
        
    }
    
</script>

<div id="contentc"></div>
<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Shot Position</th>
      <th>Shot Result</th>
      <th>Ship ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.userid %></td>
        <td><%= game.shot_position %></td>
        <td><%= game.shot_result %></td>
        <td><%= game.ship %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @game.userid %>
</p>

<p>
  <strong>Shot position:</strong>
  <%= @game.shot_position %>
</p>

<p>
  <strong>Shot result:</strong>
  <%= @game.shot_result %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Battleship</title>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!--<script src="../../assets/javascripts/fabric.min.js">-->
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
    body {
        background: lightblue;
    }

    canvas {
        background: #fff;
        margin: 20px;
    }
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>